### register
curl -X 'POST' \
  'http://localhost:8081/authen/register' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "username": "admin",
  "password": "1234",
  "level": "normal"
}'


### login
curl -X 'POST' \
  'http://localhost:8081/api/v2/login' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "username": "admin",
  "password": "1234",
  "level": "normal"
}'


### get all products
curl -X 'GET' \
  'http://localhost:8081/api/v2/product' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTYyMDYxNjk3NH0.6eP2pd_F6dT5rfZ7N-dtEFknKQ45QJ8UgvR-2p-3R38'


### get product by id
curl -X 'GET' \
  'http://localhost:8081/api/v2/product/2' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTYyMDYxNjk3NH0.6eP2pd_F6dT5rfZ7N-dtEFknKQ45QJ8UgvR-2p-3R38'


### add product
curl -X 'POST' \
  'http://localhost:8081/api/v2/product/' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTYyMDQ1NjkwMH0.r94Alr2P8Ruw_3tT4ZfK-03c76vNfuGbN6a7ZjQB0kM' \
  -d '{   
  "name": "I am lek",
  "stock": 10,
  "price": 30,
  "image": "test.jpg"
}'

### update product
curl -X 'PUT' \
  'http://localhost:8081/product/' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTYyMDQ1NjkwMH0.r94Alr2P8Ruw_3tT4ZfK-03c76vNfuGbN6a7ZjQB0kM' \
  -d '{   
  "id": "15",
  "name": "kan",
  "stock": 11,
  "price": 33,
  "image": "2test.jpg"
}'


### Delete product by id
curl -X 'DELETE' \
  'http://localhost:8081/product/27' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTYyMDQ2NTAyM30.DcHExvDZYoMiyc1X1dLtOHd2pNtxp7VLe7MtuFNCaAc'



### Insert Project
curl -X 'POST' \
  'http://localhost:8081/api/v2/product/' \
  -H 'accept: application/json' \
  -H 'Content-Type: multipart/form-data' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTYyMDYxNjk3NH0.6eP2pd_F6dT5rfZ7N-dtEFknKQ45QJ8UgvR-2p-3R38' \
  -F 'image=@test.jpg;type=image/jpeg' \
  -F 'name=1' \
  -F 'price=2' \
  -F 'stock=3'


### Update Project
curl -X 'PUT' \
  'http://localhost:8081/api/v2/product/' \
  -H 'accept: application/json' \
  -H 'Content-Type: multipart/form-data' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTYyMDYxNjk3NH0.6eP2pd_F6dT5rfZ7N-dtEFknKQ45QJ8UgvR-2p-3R38' \
  -F 'image=@test2.jpg;type=image/jpeg' \
  -F 'id=26' \
  -F 'name=test test' \
  -F 'price=20' \
  -F 'stock=30'  


### get all transactions
curl -X 'GET' \
  'http://localhost:8081/api/v2/transaction' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTYyMDYxNjk3NH0.6eP2pd_F6dT5rfZ7N-dtEFknKQ45QJ8UgvR-2p-3R38'
