### register
curl -X 'POST' \
  'http://localhost:8000/authen/register' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "username": "admin",
  "password": "1234",
  "level": "normal"
}'


### login
curl -X 'POST' \
  'http://localhost:8000/authen/login' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "username": "admin",
  "password": "1234",
  "level": "normal"
}'


### item
curl -X 'GET' \
  'http://localhost:8000/authen/items' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTYxODQ4ODgyMn0.2dqpZfUElY3rt4MbyG47Kaw9K-S7q5J-7Yodct3y8Sw'
