### register
curl -X 'POST' \
  'http://localhost:8000/authen/register' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "username": "admin",
  "password": "1234",
  "level": "normal"
}'


### login
curl -X 'POST' \
  'http://localhost:8000/authen/login' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "username": "admin",
  "password": "1234",
  "level": "normal"
}'


### get all products
curl -X 'GET' \
  'http://localhost:8000/product' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTYxODY1Mjg4Mn0.IOQTyyhVm_1UKodGemYq4d9OoHkH8MlEXZvuh9CljMY'


### get product by id
curl -X 'GET' \
  'http://localhost:8000/product/2' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTYxODY1Mjg4Mn0.IOQTyyhVm_1UKodGemYq4d9OoHkH8MlEXZvuh9CljMY'


### add product
curl -X 'POST' \
  'http://localhost:8000/product/' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTYyMDQ1NjkwMH0.r94Alr2P8Ruw_3tT4ZfK-03c76vNfuGbN6a7ZjQB0kM' \
  -d '{   
  "name": "I am lek",
  "stock": 10,
  "price": 30,
  "image": "test.jpg"
}'

### update product
curl -X 'PUT' \
  'http://localhost:8000/product/' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTYyMDQ1NjkwMH0.r94Alr2P8Ruw_3tT4ZfK-03c76vNfuGbN6a7ZjQB0kM' \
  -d '{   
  "id": "15",
  "name": "kan",
  "stock": 11,
  "price": 33,
  "image": "2test.jpg"
}'


### Delete product by id
curl -X 'DELETE' \
  'http://localhost:8000/product/16' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTYyMDQ2NTAyM30.DcHExvDZYoMiyc1X1dLtOHd2pNtxp7VLe7MtuFNCaAc'

### Upload file
curl -X 'POST' \
  'http://localhost:8000/product/files' \
  -H 'accept: application/json' \
  -H 'Content-Type: multipart/form-data' \
  -F 'file=@2021_python.png;type=image/png' \
  -F 'token=444'

### Upload file
curl -X 'POST' \
  'http://localhost:8000/product/files' \
  -H 'accept: application/json' \
  -H 'Content-Type: multipart/form-data' \
  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTYyMDQ2NTAyM30.DcHExvDZYoMiyc1X1dLtOHd2pNtxp7VLe7MtuFNCaAc' \
  -F 'file=@./test.jpg;type=image/jpeg' \
  -F 'token=1234'


### Create 
POST http://localhost:8000/product/files HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="token";

1234
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="test.jpg"
Content-Type: image/png

< ./test.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--